Fix help and introduce 'quiet' option

diff --git a/btrfsBackup b/btrfsBackup
--- a/btrfsBackup
+++ b/btrfsBackup
@@ -1,12 +1,17 @@
 #!/bin/bash
 
+version="1.0"
+programName=`echo $0|rev|cut -d '/' -f1|rev`
+options="nlyYcq"
+
 printUsage() {
     echo "Usage: "
-    echo "" `echo $0|rev|cut -d '/' -f1|rev` " [options] id [backup directory]"
-    echo "" `echo $0|rev|cut -d '/' -f1|rev` " -n [options] [backup directory]"
+    echo "$programName [-h|-v]"
+    echo "$programName [-$options] <id> [backup directory]"
+    echo "$programName -n [-$options] [backup directory]"
     echo "Backup /home and / btrfs subvolumes to backup directory"
-    echo "<backup directory> must be a btrfs filesystem;
- backup will be named <backup directory>/<id>[r|h]date, so that incremental backups are possible.
+    echo "<backup directory> must be a btrfs filesystem.
+Backup will be named <backup directory>/<id>[r|h]date, so that incremental backups are possible; this however only allows one backup per day: if this doesn't fit your needs edit the script.
 <id> is a string used to distinguish backups of different system in the same directory"
     echo "Options:
 -h: print this help and exit
@@ -15,6 +20,7 @@ printUsage() {
 -l: local, do not send subvolumes to a backup filesystem
 -y: assume yes, continue without prompting if no errors occur
 -Y: assume yes, never prompt
+-q: quiet, don't print information about operations
 -c: continue, do not abort after a non fatal error"
     echo "exit codes
 0 success
@@ -74,17 +80,25 @@ askConfirmation() {
     fi
 }
 
+printMessage() {
+    if [ "$verbose" = "true" ]
+    then
+        echo "$1"
+    fi
+}
+
 forceid=true            # force nonempty id by default
 local=false             # send to backup fs by default
 exitOnError=true        # exit on error by default
+verbose=true            # write information on operation by default
 errorFlag=false         # no errors since now
 assumeyes=false         # don't prompt unless there are errors
 assumeYes=false         # don't prompt
 
 
-while getopts hvnlcyY options
+while getopts $options currentOption
 do
-    case $options in
+    case $currentOption in
 	h) printUsage
 	   exit 0;;
 	v) printVersion
@@ -94,6 +108,8 @@ do
         c) exitOnError=false;;
         y) assumeyes=true;;
         Y) assumeYes=true;;
+        q) verbose=false;;
+        *) printWarning "Unrecognised option, check that all possible options are managed correctly!"
     esac
 done
 
@@ -117,27 +133,35 @@ then
     bkdir=/mnt/backup/
 fi
 
+
 if [ "$local" = "false" ]
 then
+    printMessage "Attempting to mount $bkdir""..."
     mountpoint -q $bkdir || ( mount $bkdir  && mountpoint -q $bkdir)  || emitError $? "Backup directory is not a mountpoint"
+else
+    printMessage "Not mounting $bkdir as requested"
 fi
+
+printMessage "Trying to determine old volume names""..."
 
 homevol=$(btrfs subvolume list / |grep "$id"h|rev|cut -d ' ' -f1|rev)
 rootvol=$(btrfs subvolume list / |grep "$id"r|rev|cut -d ' ' -f1|rev)
 
 if [[ `echo $homevol | wc -l` != 1 ]]
 then
-    error 66 "Old home subvolume not found: send command will fail " 
+    error 66 "Old home subvolume not found: send command will fail" 
 fi
 if [[ `echo $rootvol | wc -l` != 1 ]]
 then
-    error 66 "Old root subvolume not found: send command will fail " 
+    error 66 "Old root subvolume not found: send command will fail" 
 fi
+
+printMessage "Checking that no backup volume with the same name already exist""..."
 
 dateid=$(date -u +%y%m%d)
 if [[ -n $(btrfs subvolume list / |grep $dateid) ]]
 then
-    echo "backup subvolume may already exist"
+    echo "Backup volume may already exist"
     fatal 66
 fi
 
@@ -151,24 +175,22 @@ commandr="btrfs send -p /svols/$rootvol /svols/$id"r"$dateid | btrfs receive /mn
 
 if [ "$local" = "false" ]
 then
-    echo "About to execute:"
-    echo $commandh
-    echo $commandr
+    printMessage "About to execute:"
+    printMessage $commandh
+    printMessage $commandr
 fi
-echo "Existing subvolumes:"
-btrfs subvolume list /
+
+printMessage "Existing subvolumes: $(btrfs subvolume list /)"
 askConfirmation || fatal 68
 
 if [ "$local" = "false" ]
 then
     eval $commandh || error 69 "Sending home failed"
-    eval $commandr || error 69 "Sending root failed" 
+    eval $commandr || error 69 "Sending root failed"
 fi
 
-echo "About to delete old subvolumes; subvolumes in /:"
-btrfs subvolume list /
-echo "subvolumes in /mnt/backup:"
-btrfs subvolume list /mnt/backup/ | grep $dateid
+printMessage "About to delete old subvolumes; subvolumes in /: $(btrfs subvolume list /)"
+printMessage "subvolumes in /mnt/backup: $(btrfs subvolume list /mnt/backup/ | grep $dateid)"
 askConfirmation ||fatal 68
 
 btrfs subvolume delete /svols/$homevol && btrfs subvolume delete /svols/$rootvol || emitError 70 "Delete commnd failed"
